# Generated by Django 3.2.3 on 2021-08-24 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfQuestions', models.IntegerField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('subject', models.CharField(choices=[('P', 'Physics'), ('C', 'Chemistry'), ('M', 'Mathematics'), ('B', 'Biology'), ('E', 'English')], default='P', max_length=200)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=200, null=True)),
                ('answer', models.TextField(blank=True, null=True)),
                ('uniqueID', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('subject', models.CharField(choices=[('P', 'Physics'), ('C', 'Chemistry'), ('M', 'Mathematics'), ('B', 'Biology'), ('E', 'English')], default='P', max_length=200)),
                ('test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='qna.test')),
            ],
        ),
    ]
